version: '3.8'
services:
  metering-backend:
    build:
      context: ./my-metering-be
      dockerfile: Dockerfile
    container_name: metering-backend
    image: 'metering-backend:latest'
    ports:
      - "8080:8080"
    working_dir: /metering
    volumes:
      - ./my-metering-be:/metering
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

  metering-frontend:
    build:
      context: ./my-metering-fe
      dockerfile: Dockerfile
    container_name: metering-frontend
    image: 'metering-frontend:latest'
    ports:
      - "3000:80"  # Maps container's port 80 (nginx) to host port 3000
    depends_on:
      - metering-backend

  postgres:
    container_name: metering-db-postgres
    image: postgres
    restart: always
    volumes:
      - ./my-metering-be/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: metering-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  metering:
